# database init, supports mysql too
database: h2

# Logging
logging:
  level:
    org.springframework: INFO
#    org.springframework.web=DEBUG
#    org.springframework.context.annotation=TRACE

spring:
  datasource:
    schema: classpath*:db/${database}/schema.sql
    data: classpath*:db/${database}/data.sql

# Web
  thymeleaf:
    mode: HTML

# JPA
  jpa:
    hibernate.ddl-auto: none
    open-in-view: false

# Internationalization
  messages:
    basename: messages/messages

  security:
    oauth2:
      client:
        registration:
          petstore-clinic:
            client-id: vismahome
            client-secret: dPteylUyhFvtzpBbWanaaxtlIdSWRihTNIOgtPcSqMhMOaNTYlbXpLYcITXcRLHk
            client-name: visma
            scope: openid
            redirect-uri: https%3A%2F%2Fapi.home.stag.visma.com%2Fhome%2Frest%2Fsso%2Flogin
            nonce: 8ZVEq6t3&state=uZTvVbKxwn7aToi0WC99jqunHFI5D5aI
            response_type: code
            response_mode: form_post
            client-authentication-method: basic
            authorization-grant-type: authorization_code
            provider: connectid-provider
        provider:
          connectid-provider:
            authorization-uri: https://connect.identity.stagaws.visma.com/connect/authorize
            token-uri: https://connect.identity.stagaws.visma.com/connect/token
            user-info-uri: https://connect.identity.stagaws.visma.com/connect/userinfo



